"""Initial migration

Revision ID: 79391ba35ef6
Revises: 
Create Date: 2026-01-02 23:11:05.451829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79391ba35ef6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_company_id', sa.Integer(), nullable=False),
    sa.Column('practice_area_id', sa.Integer(), nullable=False),
    sa.Column('incoming_fees', sa.Integer(), nullable=False),
    sa.Column('fees_collected', sa.Integer(), nullable=False),
    sa.Column('new_mandates', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_company_id'], ['insurance_companies.id'], ),
    sa.ForeignKeyConstraint(['practice_area_id'], ['practice_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insurance_company_id', sa.Integer(), nullable=False),
    sa.Column('practice_area_id', sa.Integer(), nullable=False),
    sa.Column('department_visited', sa.String(), nullable=False),
    sa.Column('visited_key_personnel', sa.String(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('report_content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_company_id'], ['insurance_companies.id'], ),
    sa.ForeignKeyConstraint(['practice_area_id'], ['practice_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('kpis')
    op.drop_table('practice_areas')
    op.drop_table('insurance_companies')
    # ### end Alembic commands ###
